### ISSUE TITLE
Mob grief false rule + Fireballs/Ghasts = Crash

### ISSUE THREAD

**Issue by CloWnicide** [RicardoTheCoder/YetAnotherCore#2]
Unable to figure out why it keeps doing this, but anytime I have the mod installed into my directory, any fireballs from entities cause the game to crash. After removing the mod (which unfortunately also includes MiniMoos), the issue goes away with any fireball entities being ticked. If needed, I can post the entire report.

<details>
  <summary>Click to enlarge</summary>
---- Minecraft Crash Report ----

WARNING: coremods are present:
  CoreMod (Aroma1997Core-1.12.2-2.0.0.0.b150.jar)
  MicdoodlePlugin (MicdoodleCore-1.12.2-4.0.1.177.jar)
  LoadingPlugin (Quark-r1.4-123.jar)
  RandomPatches (randompatches-1.12.2-1.1.0.0.jar)
  Do not report to Forge! Remove FoamFixAPI (or replace with FoamFixAPI-Lawful) and try again. (foamfix-0.9.9.1-1.12.2-anarchy.jar)
  FCFMLCorePlugin (FinderCompass-1.12.1.jar)
  LoadingPlugin (Bloodmoon-MC1.12.2-1.5.3.jar)
  MalisisCorePlugin (malisiscore-1.12.2-6.4.0.jar)
  ShetiPhian-ASM (shetiphiancore-1.12.0-3.5.6.jar)
  FMLPlugin (elulib-0.1.12.jar)
  Inventory Tweaks Coremod (InventoryTweaks-1.64-dev.jar)
  EECore (ExpandedEquivalence-1.12.2-4r.jar)
  IELoadingPlugin (ImmersiveEngineering-core-0.12-82.jar)
  LoadingPlugin (ResourceLoader-MC1.12.1-1.5.3.jar)
  llibrary (llibrary-core-1.0.6-1.12.2.jar)
  TransformerLoader (OpenComputers-MC1.12.2-1.7.2.67.jar)
  AppleCore (AppleCore-mc1.12.2-3.1.1.jar)
  SHLoadingPlugin (ScalingHealth-1.12-1.3.16-99.jar)
  LibrarianLib Plugin (librarianlib-1.12.2-4.9.jar)
  CTMCorePlugin (CTM-MC1.12-0.2.3.12.jar)
  AstralCore (astralsorcery-1.12.2-1.8.10.jar)
  BedPatch (bedpatch-2.2-1.12.2.jar)
  ColytraLoadingPlugin (colytra-1.12.2-1.0.4.3.jar)
  OpenModsCorePlugin (OpenModsLib-1.12.2-0.11.5.jar)
  Plugin (NotEnoughIDs-1.5.4.2.jar)
  EnderCorePlugin (EnderCore-1.12.2-0.5.22.jar)
  HammerCoreCore (HammerCore-1.12.2-1.9.9.11.jar)
  Wizardry Plugin (wizardry-0.8.5.jar)
  ISCore (ImprovableSkills_1.12.2-3.4.1r.jar)
  AdvancedRocketryPlugin (AdvancedRocketry-1.12.2-1.4.0-80.jar)
  ForgelinPlugin (Forgelin-1.6.0.jar)
  TheBetweenlandsLoadingPlugin (TheBetweenlands-3.3.8-core.jar)
Contact their authors BEFORE contacting forge

// Hi. I'm Minecraft, and I'm a crashaholic.

Time: 6/13/18 12:34 AM
Description: Ticking entity

java.lang.NullPointerException: Ticking entity
	at com.ricardothecoder.yac.library.gamerules.rules.grief.ExplosionGrief.apply(ExplosionGrief.java:52)
	at com.ricardothecoder.yac.library.gamerules.RuleControl.onExplosionDetonate(RuleControl.java:38)
	at net.minecraftforge.fml.common.eventhandler.ASMEventHandler_25_RuleControl_onExplosionDetonate_Detonate.invoke(.dynamic)
	at net.minecraftforge.fml.common.eventhandler.ASMEventHandler.invoke(ASMEventHandler.java:90)
	at net.minecraftforge.fml.common.eventhandler.EventBus.post(EventBus.java:182)
	at net.minecraftforge.event.ForgeEventFactory.onExplosionDetonate(ForgeEventFactory.java:558)
	at net.minecraft.world.Explosion.func_77278_a(Explosion.java:134)
	at net.minecraft.world.WorldServer.func_72885_a(WorldServer.java:1169)
	at net.minecraft.entity.projectile.EntityLargeFireball.func_70227_a(EntityLargeFireball.java:44)
	at net.minecraft.entity.projectile.EntityFireball.func_70071_h_(EntityFireball.java:98)
	at net.minecraft.world.World.func_72866_a(World.java:1990)
	at net.minecraft.world.WorldServer.func_72866_a(WorldServer.java:832)
	at net.minecraft.world.World.func_72870_g(World.java:1952)
	at net.minecraft.world.World.func_72939_s(World.java:1756)
	at net.minecraft.world.WorldServer.func_72939_s(WorldServer.java:613)
	at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:767)
	at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:668)
	at net.minecraft.server.integrated.IntegratedServer.func_71217_p(IntegratedServer.java:252)
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:526)
	at java.lang.Thread.run(Thread.java:745)

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: Server thread
Stacktrace:
	at com.ricardothecoder.yac.library.gamerules.rules.grief.ExplosionGrief.apply(ExplosionGrief.java:52)
	at com.ricardothecoder.yac.library.gamerules.RuleControl.onExplosionDetonate(RuleControl.java:38)
	at net.minecraftforge.fml.common.eventhandler.ASMEventHandler_25_RuleControl_onExplosionDetonate_Detonate.invoke(.dynamic)
	at net.minecraftforge.fml.common.eventhandler.ASMEventHandler.invoke(ASMEventHandler.java:90)
	at net.minecraftforge.fml.common.eventhandler.EventBus.post(EventBus.java:182)
	at net.minecraftforge.event.ForgeEventFactory.onExplosionDetonate(ForgeEventFactory.java:558)
	at net.minecraft.world.Explosion.func_77278_a(Explosion.java:134)
	at net.minecraft.world.WorldServer.func_72885_a(WorldServer.java:1169)
	at net.minecraft.entity.projectile.EntityLargeFireball.func_70227_a(EntityLargeFireball.java:44)
	at net.minecraft.entity.projectile.EntityFireball.func_70071_h_(EntityFireball.java:98)
	at net.minecraft.world.World.func_72866_a(World.java:1990)
	at net.minecraft.world.WorldServer.func_72866_a(WorldServer.java:832)
	at net.minecraft.world.World.func_72870_g(World.java:1952)

-- Entity being ticked --
Details:
	Entity Type: minecraft:fireball (net.minecraft.entity.projectile.EntityLargeFireball)
	Entity ID: 432257
	Entity Name: Fireball
	Entity's Exact location: 846.19, 64.46, 464.53
	Entity's Block location: World: (846,64,464), Chunk: (at 14,4,0 in 52,29; contains blocks 832,0,464 to 847,255,479), Region: (1,0; contains chunks 32,0 to 63,31, blocks 512,0,0 to 1023,255,511)
	Entity's Momentum: 0.26, -0.03, -1.01
	Entity's Passengers: []
	Entity's Vehicle: ~~ERROR~~ NullPointerException: null
Stacktrace:
	at net.minecraft.world.World.func_72939_s(World.java:1756)
	at net.minecraft.world.WorldServer.func_72939_s(WorldServer.java:613)

-- Affected level --
Details:
	Level name: Let's Survive
	All players: 1 total; [GCEntityPlayerMP['Matricide'/1000, l='Let's Survive', x=840.61, y=63.00, z=468.46]]
	Chunk stats: ServerChunkCache: 1281 Drop: 0
	Level seed: -533884313
	Level generator: ID 00 - default, ver 1. Features enabled: true
	Level generator options: {"diamondSize":8,"lapisCenterHeight":16,"lavaLakeChance":80,"redstoneMaxHeight":16,"diamondMaxHeight":16,"coalMaxHeight":128,"coalMinHeight":0,"seaLevel":63,"graniteCount":10,"riverSize":4,"gravelMinHeight":0,"graniteSize":33,"redstoneSize":8,"fixedBiome":-1,"waterLakeChance":4,"dioriteMinHeight":0,"andesiteCount":10,"graniteMaxHeight":80,"redstoneMinHeight":0,"lapisSize":7,"dirtCount":10,"ironMinHeight":0,"dioriteMaxHeight":80,"coalCount":20,"gravelCount":8,"coalSize":17,"gravelSize":33,"ironMaxHeight":64,"lapisSpread":16,"dioriteCount":10,"andesiteSize":33,"biomeSize":4,"graniteMinHeight":0,"goldCount":2,"diamondCount":1,"dirtSize":33,"gravelMaxHeight":256,"goldSize":9,"ironCount":20,"diamondMinHeight":0,"ironSize":9,"redstoneCount":8,"andesiteMinHeight":0,"dioriteSize":33,"goldMaxHeight":32,"dungeonChance":8,"andesiteMaxHeight":80,"dirtMinHeight":0,"lapisCount":1,"goldMinHeight":0,"dirtMaxHeight":256,"lowerLimitScale":512.0,"biomeDepthOffset":0.0,"upperLimitScale":512.0,"heightScale":684.412,"biomeScaleWeight":1.0,"biomeDepthWeight":1.0,"mainNoiseScaleZ":80.0,"mainNoiseScaleY":160.0,"depthNoiseScaleX":200.0,"mainNoiseScaleX":80.0,"baseSize":8.5,"depthNoiseScaleZ":200.0,"stretchY":12.0,"depthNoiseScaleExponent":0.5,"biomeScaleOffset":0.0,"coordinateScale":684.412,"useStrongholds":true,"useMineShafts":true,"useTemples":true,"useLavaOceans":false,"useCaves":true,"useWaterLakes":true,"useLavaLakes":true,"useMonuments":true,"useRavines":true,"useDungeons":true,"useVillages":true}
	Level spawn location: World: (508,71,332), Chunk: (at 12,4,12 in 31,20; contains blocks 496,0,320 to 511,255,335), Region: (0,0; contains chunks 0,0 to 31,31, blocks 0,0,0 to 511,255,511)
	Level time: 11628516 game time, 14077804 day time
	Level dimension: 0
	Level storage version: 0x04ABD - Anvil
	Level weather: Rain time: 17065 (now: true), thunder time: 27308 (now: false)
	Level game mode: Game mode: survival (ID 0). Hardcore: false. Cheats: true
Stacktrace:
	at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:767)
	at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:668)
	at net.minecraft.server.integrated.IntegratedServer.func_71217_p(IntegratedServer.java:252)
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:526)
	at java.lang.Thread.run(Thread.java:745)
</details>

**Comment by IRicTheCoder** [comment]
@CloWnicide Have you updated the Core to the latest version? Should be in beta yet so might not show on curse as an update. As this should be fixed when it comes to that, however I will take another look into it.

**Comment by CloWnicide** [comment]
Everything is updated to the latest, but I may have fixed the issue as when I updated the gamerule in-game for creeperGrief, but I also input /creepergrief along with /creeperGrief and it seemed to be causeing the issue. Removed both and set explosionGrief to true, once I go back into the Nether I will be able to figure out if the issue is fully resolved.

**Comment by IRicTheCoder** [comment]
I will try and find a way to prevent any issues from this point on and allow for both lower, upper and camel cased words has names of the game rule so it will not create conflicts from multiple ones being added.

But do tell if it gets resolved
